
### SIGNUP ###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   
  "name": "Astolfo" ,
  "email": "astolfo@gmail.com",
  "password" :"astolfo123",
  "role": "NORMAL" 
}


### Login ###
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "kayoceshar@gmail.com",
  "password" :"kayo123"
}



### Register ###
POST http://localhost:3003/band/registerband
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ZmUwMDUyLTAyNDgtNDlmNC1iYzg3LTVhYzMxN2ExM2JjMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3ODkwNjQ4MSwiZXhwIjoxNjc4OTEwMDgxfQ.q5HwfZ5QueQsiKYIddyoUjwPYEwr0ZSauIMyGDvGchk
Content-Type: application/json

{
  "name": "Raça Negra",
  "musicGenre": "Pagode",
  "responsible":"Luiz Carlos"  
}


### Search Band ###
GET http://localhost:3003/band/fe40df38-2f9a-4f5e-b34b-df469f2aaf26
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOWIyZTY0LTM4ZjQtNDk0Zi05M2U2LTE0MjA2NjgwNGE3ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3ODgzNjI4MCwiZXhwIjoxNjc4ODM5ODgwfQ.OPMXFPmDlxd40OPQWMlpxw3pXapRwrQqHWiadCOYMGQ

### Add Show Day
POST http://localhost:3003/band/addshowday
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOWIyZTY0LTM4ZjQtNDk0Zi05M2U2LTE0MjA2NjgwNGE3ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwMTEyMCwiZXhwIjoxNjc5MDA0NzIwfQ.FvXpOYrEQ3lvyogd1INSPyrYvvYOi2kEFdbHJAoWpdI
Content-Type: application/json

{
  "weekDay": "Sexta",
  "startTime": 15,
  "endTime": 19,
  "bandId": "c155afe2-5241-498e-bd77-c8e358ee6512"
}




### day ###
GET http://localhost:3003/band/showsday/sexta


### create ticket
POST http://localhost:3003/band/createticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOWIyZTY0LTM4ZjQtNDk0Zi05M2U2LTE0MjA2NjgwNGE3ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwNTc3OSwiZXhwIjoxNjc5MDA5Mzc5fQ.tsf98cEYhuHKJULY0qIu-E5nUZBUvLJ9Cqa1CBQSGN0
Content-Type: application/json

{
  "name": "Show da banda Capital Inicial",
  "value": 50,
  "eventId": "15f493c6-fa2d-45ea-9521-4aa980e31149",
  "qtyStock":500
}



############ sale
POST http://localhost:3003/band/ticketsale/15f493c6-fa2d-45ea-9521-4aa980e31149
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlOWIyZTY0LTM4ZjQtNDk0Zi05M2U2LTE0MjA2NjgwNGE3ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAxMzgwOSwiZXhwIjoxNjc5MDE3NDA5fQ.8m9dx1jrRLGKkxLJ_z6M4uR4ReYmQ52ktwL-0iI28Z4
Content-Type: application/json

{
   "qty":5
}
