-- Active: 1674164268204@@35.226.146.116@3306@jbl-4416383-kayo-santos
CREATE TABLE IF NOT EXISTS TABELA_USUARIOS (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM("ADMIN", "NORMAL") NOT NULL DEFAULT "NORMAL"
);

CREATE TABLE IF NOT EXISTS TABELA_BANDAS (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  music_genre VARCHAR(255) NOT NULL,
  responsible VARCHAR(255) UNIQUE NOT NULL 
);

CREATE TABLE IF NOT EXISTS TABELA_SHOWS (
  id VARCHAR(255) PRIMARY KEY,
  week_day VARCHAR(255) NOT NULL,
  start_time INT NOT NULL,
  end_time INT NOT NULL,
  band_id VARCHAR(255) NOT NULL,
  FOREIGN KEY(band_id) REFERENCES TABELA_BANDAS(id)
);

CREATE TABLE IF NOT EXISTS TABELA_INGRESSOS (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  value INT NOT NULL,
  event_id VARCHAR(255) NOT NULL,
  qty_stock INT NOT NULL,
  sold INT NOT NULL DEFAULT 0,
  FOREIGN KEY(event_id) REFERENCES TABELA_SHOWS(id)
);

CREATE TABLE IF NOT EXISTS TABELA_GALERIA (
  id VARCHAR(255) PRIMARY KEY,
  link_photo VARCHAR(255) NOT NULL,
  event_id VARCHAR(255) NOT NULL,  
  FOREIGN KEY(event_id) REFERENCES TABELA_SHOWS(id)
);


